### ISSUE TITLE
Frame project Termostato Nextion Esphome - Home Assistant

### ISSUE THREAD

**Issue by Giuseppe-P** [Giuseppe-P/Thermostat-Esphome-Nextion-3.2-#1]
![IMG_20200504_171325](https://user-images.githubusercontent.com/15862510/80982771-0c0b6500-8e2c-11ea-923e-0a722314a267.jpg)
![IMG_20200504_171339](https://user-images.githubusercontent.com/15862510/80982779-0dd52880-8e2c-11ea-992c-8776021a4583.jpg)
![IMG_20200504_171421](https://user-images.githubusercontent.com/15862510/80982784-0f9eec00-8e2c-11ea-9e0e-151c932e8e59.jpg)
![Manual ON OFF](https://user-images.githubusercontent.com/15862510/80983071-6d333880-8e2c-11ea-8b7c-6b510ea3e4b4.jpg)
![IMG_20200504_171511](https://user-images.githubusercontent.com/15862510/80983140-86d48000-8e2c-11ea-982e-a0e2fd4ea7ad.jpg)

**Comment by vrelk** [comment]
What is the frame/case that you are using? I have been looking for something to hold the display and still have room for everything else, but haven't found anything that looks good yet.

**Comment by Giuseppe-P** [comment]
I used an electro-channel frame ... but you can use any frame ... but you have to practically modify the whole layout by modifying the images to insert in the hmi file

**Comment by Giuseppe-P** [comment]
The frame used is a common 503 cassette frame. You can use whatever you like, but remember that according to the frame you have to modify the layout images by cutting to size with paint or other software editing, and reload them again in the .hmi file
